#ifdef __cplusplus
extern "C" {
#endif
/*
ANSI C code generated by SmartEiffel The GNU Eiffel Compiler, Eiffel tools and libraries
Release 2.3 (Thursday July 11th 2007) [Antoine-Auguste Parmentier]
Copyright (C), 1994-2002 - INRIA - LORIA - ESIAL UHP Nancy 1 - FRANCE
Copyright (C), 2003-2005 - INRIA - LORIA - IUT Charlemagne Nancy 2 - FRANCE
D.COLNET, P.RIBET, C.ADRIAN, V.CROIZIER F.MERIZEN - SmartEiffel@loria.fr
http://SmartEiffel.loria.fr
C Compiler options used: -pipe
*/

#ifdef __cplusplus
}
#endif
#include "mediatheque.h"
#ifdef __cplusplus
extern "C" {
#endif
T0*ms56_117797837;

T0*se_ms(int c,char*e){
/* Allocate a Manifest STRING.*/
T7*s=new7();
s->_count=c;
s->_capacity=c+1;
s->_storage=((T9)new9(c+1));
memcpy(s->_storage,e,c+1);
return((T0*)s);}/*--*/

T0*se_string(char*e){
/* Allocate an Eiffel STRING by copying C char*e */
int c=strlen(e);
T7*s=new7();
s->_count=c;
s->_capacity=c+1;
s->_storage=((T9)new9(c+1));
memcpy(s->_storage,e,c+1);
return((T0*)s);}/*--*/

void se_msi1(void){
ms56_117797837=se_ms(10,s56_117797837);
}/*--*/

void manifest_string_mark1(void){
gc_mark7((T7*)ms56_117797837);
}/*--*/

void once_function_mark(void){
/*NON_VOID_NO_DISPATCH:*/
/*Ordinary once functions:*/
if(NULL!=oBC7split_buffer)gc_mark131((T131*)(oBC7split_buffer));
if(NULL!=oBC7string_buffer)gc_mark7((T7*)(oBC7string_buffer));
if(NULL!=oBC13io)gc_mark40((T40*)(oBC13io));
if(NULL!=oBC56string_buffer)gc_mark7((T7*)(oBC56string_buffer));
if(NULL!=oBC13std_output)gc_mark47((T47*)(oBC13std_output));
if(NULL!=oBC13std_input)gc_mark48((T48*)(oBC13std_input));
if(NULL!=oBC44last_string)gc_mark7((T7*)(oBC44last_string));
if(NULL!=oBC58time_mode_memo)gc_mark137((T137*)(oBC58time_mode_memo));
}/*--*/

void gc_start(void){
if(gc_is_off)return;
if(garbage_delayed())return;
handle(SE_HANDLE_ENTER_GC,NULL);
gcmt_tail_addr=(((char*)(gcmt[gcmt_used-1]))+(gcmt[gcmt_used-1])->size);
((gc25*)eiffel_root_object)->header.flag=FSOH_UNMARKED;
if(na_env136.store_left>0){
na_env136.store->header.size=na_env136.store_left;
na_env136.store->header.magic_flag=RSOH_FREE;
na_env136.store_left=0;
}
na_env136.chunk_list=NULL;
na_env136.store_chunk=NULL;
gc_free137=(void*)0;
if(na_env135.store_left>0){
na_env135.store->header.size=na_env135.store_left;
na_env135.store->header.magic_flag=RSOH_FREE;
na_env135.store_left=0;
}
na_env135.chunk_list=NULL;
na_env135.store_chunk=NULL;
if(na_env134.store_left>0){
na_env134.store->header.size=na_env134.store_left;
na_env134.store->header.magic_flag=RSOH_FREE;
na_env134.store_left=0;
}
na_env134.chunk_list=NULL;
na_env134.store_chunk=NULL;
if(na_env133.store_left>0){
na_env133.store->header.size=na_env133.store_left;
na_env133.store->header.magic_flag=RSOH_FREE;
na_env133.store_left=0;
}
na_env133.chunk_list=NULL;
na_env133.store_chunk=NULL;
gc_free47=(void*)0;
gc_free48=(void*)0;
gc_free61=(void*)0;
gc_free60=(void*)0;
gc_free59=(void*)0;
gc_free131=(void*)0;
gc_free62=(void*)0;
gc_free130=(void*)0;
gc_free54=(void*)0;
gc_free129=(void*)0;
gc_free55=(void*)0;
gc_free128=(void*)0;
gc_free40=(void*)0;
gc_free25=(void*)0;
if(na_env9.store_left>0){
na_env9.store->header.size=na_env9.store_left;
na_env9.store->header.magic_flag=RSOH_FREE;
na_env9.store_left=0;
}
na_env9.chunk_list=NULL;
na_env9.store_chunk=NULL;
gc_free7=(void*)0;
gc_mark25(eiffel_root_object);
manifest_string_mark1();
once_function_mark();
{int i=SE_MAXID-1;
while(i>=0){
if(g[i]!=NULL)gc_mark7(g[i]);
i--;}
}
{int i=SE_MAXID-1;
while(i>=0){
if(t[i]!=NULL)gc_mark7(t[i]);
i--;}
}
mark_stack_and_registers();
gc_sweep();
collector_counter++;
handle(SE_HANDLE_EXIT_GC,NULL);
}/*--*/
na_env na_env136={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark136};
gc137*store137=(void*)0;
int store_left137=0;
fsoc*store_chunk137=(void*)0;
gc137*gc_free137=(void*)0;
na_env na_env135={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark135};
na_env na_env134={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark134};
na_env na_env133={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark133};
gc47*store47=(void*)0;
int store_left47=0;
fsoc*store_chunk47=(void*)0;
gc47*gc_free47=(void*)0;
gc48*store48=(void*)0;
int store_left48=0;
fsoc*store_chunk48=(void*)0;
gc48*gc_free48=(void*)0;
gc61*store61=(void*)0;
int store_left61=0;
fsoc*store_chunk61=(void*)0;
gc61*gc_free61=(void*)0;
gc60*store60=(void*)0;
int store_left60=0;
fsoc*store_chunk60=(void*)0;
gc60*gc_free60=(void*)0;
gc59*store59=(void*)0;
int store_left59=0;
fsoc*store_chunk59=(void*)0;
gc59*gc_free59=(void*)0;
gc131*store131=(void*)0;
int store_left131=0;
fsoc*store_chunk131=(void*)0;
gc131*gc_free131=(void*)0;
gc62*store62=(void*)0;
int store_left62=0;
fsoc*store_chunk62=(void*)0;
gc62*gc_free62=(void*)0;
gc130*store130=(void*)0;
int store_left130=0;
fsoc*store_chunk130=(void*)0;
gc130*gc_free130=(void*)0;
gc54*store54=(void*)0;
int store_left54=0;
fsoc*store_chunk54=(void*)0;
gc54*gc_free54=(void*)0;
gc129*store129=(void*)0;
int store_left129=0;
fsoc*store_chunk129=(void*)0;
gc129*gc_free129=(void*)0;
gc55*store55=(void*)0;
int store_left55=0;
fsoc*store_chunk55=(void*)0;
gc55*gc_free55=(void*)0;
gc128*store128=(void*)0;
int store_left128=0;
fsoc*store_chunk128=(void*)0;
gc128*gc_free128=(void*)0;
gc40*store40=(void*)0;
int store_left40=0;
fsoc*store_chunk40=(void*)0;
gc40*gc_free40=(void*)0;
gc25*store25=(void*)0;
int store_left25=0;
fsoc*store_chunk25=(void*)0;
gc25*gc_free25=(void*)0;
na_env na_env9={0,NULL,NULL,NULL,(void(*)(T0*))gc_mark9};
gc7*store7=(void*)0;
int store_left7=0;
fsoc*store_chunk7=(void*)0;
gc7*gc_free7=(void*)0;

void gc_mark136(T136 o){
if(NULL==gc_find_chunk(o))
return; /* external NA */
{rsoh*h=((rsoh*)o)-1;
 if((h->header.magic_flag)==RSOH_UNMARKED){
    h->header.magic_flag=RSOH_MARKED;
    {T0* e;
T0**p=((void*)(o+((((h->header.size)-sizeof(rsoh))/sizeof(e))-1)));
for(;((void*)p)>=((void*)o);p--){
e=*p;
if(NULL!=e)gc_mark7((T7*)(e));
}}}}
}/*--*/

T136 new136(unsigned int size){
size=(size*sizeof(T0*))+sizeof(rsoh);
size=((size+(sizeof(double)-1))&~(sizeof(double)-1));
if (size<=(na_env136.store_left)){
rsoh*r=na_env136.store;
na_env136.store_left-=size;
if(na_env136.store_left>sizeof(rsoh)){
r->header.size=size;
na_env136.store=((rsoh*)(((char*)(na_env136.store))+size));
}
else {
r->header.size=size+na_env136.store_left;
na_env136.store_left=0;
}
(r->header.magic_flag)=RSOH_UNMARKED;
((void)memset((r+1),0,r->header.size-sizeof(rsoh)));
return((T136)(r+1));
}
return((T136)new_na(&na_env136,size));
}/*--*/

void gc_sweep137(fsoc*c){
gc137*o1,*o2;
o1=((gc137*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store137;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free137;
gc_free137=o1;
}
}
}
else{
int dead=1;
gc137* old_gc_free = gc_free137;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free137;
gc_free137=o1;
}
}
if (dead){
gc_free137 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark137(T137*o){
se_gc_check_id(o,137);
{
((gc137*)o)->header.flag=FSOH_MARKED;
}
}/*--*/

void gc_align_mark137(fsoc*c,gc137*p){
gc137*b=((gc137*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store137)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T137*o=(&(p->object));
((gc137*)o)->header.flag=FSOH_MARKED;
}
}
}/*--*/
fsoc H137={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark137,
(void(*)(mch*))gc_sweep137},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc137))-1)};

T137*new137(void){
gc137*n;
fsoc*c;
if(store_left137>1){
store_left137--;
n=store137++;
}
else if(gc_free137!=NULL){
n=gc_free137;
gc_free137=n->header.next;
}
else if(store_left137==1){
store_left137=0;
store_chunk137->header.state_type=FSO_USED_CHUNK;
n=store137++;
}
else{
c=gc_fsoc_get1();
if(gc_free137!=NULL){
n=gc_free137;
gc_free137=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk137=c;
*store_chunk137=H137;
store137=((gc137*)(&(store_chunk137->first_object)));
store_left137=H137.count_minus_one;
n=store137++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M137;
return((T137*)n);
}/*--*/

void gc_mark135(T135 o){
if(NULL==gc_find_chunk(o))
return; /* external NA */
{rsoh*h=((rsoh*)o)-1;
 if((h->header.magic_flag)==RSOH_UNMARKED){
    h->header.magic_flag=RSOH_MARKED;
    {T0* e;
T0**p=((void*)(o+((((h->header.size)-sizeof(rsoh))/sizeof(e))-1)));
for(;((void*)p)>=((void*)o);p--){
e=*p;
if(NULL!=e)Xgc_mark49((T0*)(e));
}}}}
}/*--*/

T135 new135(unsigned int size){
size=(size*sizeof(T0*))+sizeof(rsoh);
size=((size+(sizeof(double)-1))&~(sizeof(double)-1));
if (size<=(na_env135.store_left)){
rsoh*r=na_env135.store;
na_env135.store_left-=size;
if(na_env135.store_left>sizeof(rsoh)){
r->header.size=size;
na_env135.store=((rsoh*)(((char*)(na_env135.store))+size));
}
else {
r->header.size=size+na_env135.store_left;
na_env135.store_left=0;
}
(r->header.magic_flag)=RSOH_UNMARKED;
((void)memset((r+1),0,r->header.size-sizeof(rsoh)));
return((T135)(r+1));
}
return((T135)new_na(&na_env135,size));
}/*--*/

void gc_mark134(T134 o){
if(NULL==gc_find_chunk(o))
return; /* external NA */
{rsoh*h=((rsoh*)o)-1;
 if((h->header.magic_flag)==RSOH_UNMARKED){
    h->header.magic_flag=RSOH_MARKED;
    {T0* e;
T0**p=((void*)(o+((((h->header.size)-sizeof(rsoh))/sizeof(e))-1)));
for(;((void*)p)>=((void*)o);p--){
e=*p;
if(NULL!=e)Xgc_mark54((T0*)(e));
}}}}
}/*--*/

T134 new134(unsigned int size){
size=(size*sizeof(T0*))+sizeof(rsoh);
size=((size+(sizeof(double)-1))&~(sizeof(double)-1));
if (size<=(na_env134.store_left)){
rsoh*r=na_env134.store;
na_env134.store_left-=size;
if(na_env134.store_left>sizeof(rsoh)){
r->header.size=size;
na_env134.store=((rsoh*)(((char*)(na_env134.store))+size));
}
else {
r->header.size=size+na_env134.store_left;
na_env134.store_left=0;
}
(r->header.magic_flag)=RSOH_UNMARKED;
((void)memset((r+1),0,r->header.size-sizeof(rsoh)));
return((T134)(r+1));
}
return((T134)new_na(&na_env134,size));
}/*--*/

void gc_mark133(T133 o){
if(NULL==gc_find_chunk(o))
return; /* external NA */
{rsoh*h=((rsoh*)o)-1;
 if((h->header.magic_flag)==RSOH_UNMARKED){
    h->header.magic_flag=RSOH_MARKED;
    {T0* e;
T0**p=((void*)(o+((((h->header.size)-sizeof(rsoh))/sizeof(e))-1)));
for(;((void*)p)>=((void*)o);p--){
e=*p;
if(NULL!=e)gc_mark55((T55*)(e));
}}}}
}/*--*/

T133 new133(unsigned int size){
size=(size*sizeof(T0*))+sizeof(rsoh);
size=((size+(sizeof(double)-1))&~(sizeof(double)-1));
if (size<=(na_env133.store_left)){
rsoh*r=na_env133.store;
na_env133.store_left-=size;
if(na_env133.store_left>sizeof(rsoh)){
r->header.size=size;
na_env133.store=((rsoh*)(((char*)(na_env133.store))+size));
}
else {
r->header.size=size+na_env133.store_left;
na_env133.store_left=0;
}
(r->header.magic_flag)=RSOH_UNMARKED;
((void)memset((r+1),0,r->header.size-sizeof(rsoh)));
return((T133)(r+1));
}
return((T133)new_na(&na_env133,size));
}/*--*/

void gc_sweep47(fsoc*c){
gc47*o1,*o2;
o1=((gc47*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store47;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free47;
gc_free47=o1;
}
}
}
else{
int dead=1;
gc47* old_gc_free = gc_free47;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free47;
gc_free47=o1;
}
}
if (dead){
gc_free47 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark47(T47*o){
se_gc_check_id(o,47);
{
if(((gc47*)o)->header.flag==FSOH_UNMARKED){
((gc47*)o)->header.flag=FSOH_MARKED;
/*i4p*/if(NULL!=o->_buffer)gc_mark9((o->_buffer));
/*i4p*/}
}
}/*--*/

void gc_align_mark47(fsoc*c,gc47*p){
gc47*b=((gc47*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store47)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T47*o=(&(p->object));
((gc47*)o)->header.flag=FSOH_MARKED;
/*i4p*/if(NULL!=o->_buffer)gc_mark9((o->_buffer));
/*i4p*/}
}
}/*--*/
fsoc H47={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark47,
(void(*)(mch*))gc_sweep47},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc47))-1)};

T47*new47(void){
gc47*n;
fsoc*c;
if(store_left47>1){
store_left47--;
n=store47++;
}
else if(gc_free47!=NULL){
n=gc_free47;
gc_free47=n->header.next;
}
else if(store_left47==1){
store_left47=0;
store_chunk47->header.state_type=FSO_USED_CHUNK;
n=store47++;
}
else{
c=gc_fsoc_get1();
if(gc_free47!=NULL){
n=gc_free47;
gc_free47=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk47=c;
*store_chunk47=H47;
store47=((gc47*)(&(store_chunk47->first_object)));
store_left47=H47.count_minus_one;
n=store47++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M47;
return((T47*)n);
}/*--*/

void gc_sweep48(fsoc*c){
gc48*o1,*o2;
o1=((gc48*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store48;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free48;
gc_free48=o1;
}
}
}
else{
int dead=1;
gc48* old_gc_free = gc_free48;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free48;
gc_free48=o1;
}
}
if (dead){
gc_free48 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark48(T48*o){
se_gc_check_id(o,48);
{
if(((gc48*)o)->header.flag==FSOH_UNMARKED){
((gc48*)o)->header.flag=FSOH_MARKED;
/*i2p*/if(NULL!=o->_buffer)gc_mark9((o->_buffer));
}
}
}/*--*/

void gc_align_mark48(fsoc*c,gc48*p){
gc48*b=((gc48*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store48)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T48*o=(&(p->object));
((gc48*)o)->header.flag=FSOH_MARKED;
/*i2p*/if(NULL!=o->_buffer)gc_mark9((o->_buffer));
}
}
}/*--*/
fsoc H48={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark48,
(void(*)(mch*))gc_sweep48},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc48))-1)};

T48*new48(void){
gc48*n;
fsoc*c;
if(store_left48>1){
store_left48--;
n=store48++;
}
else if(gc_free48!=NULL){
n=gc_free48;
gc_free48=n->header.next;
}
else if(store_left48==1){
store_left48=0;
store_chunk48->header.state_type=FSO_USED_CHUNK;
n=store48++;
}
else{
c=gc_fsoc_get1();
if(gc_free48!=NULL){
n=gc_free48;
gc_free48=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk48=c;
*store_chunk48=H48;
store48=((gc48*)(&(store_chunk48->first_object)));
store_left48=H48.count_minus_one;
n=store48++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M48;
return((T48*)n);
}/*--*/

void gc_sweep61(fsoc*c){
gc61*o1,*o2;
o1=((gc61*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store61;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free61;
gc_free61=o1;
}
}
}
else{
int dead=1;
gc61* old_gc_free = gc_free61;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free61;
gc_free61=o1;
}
}
if (dead){
gc_free61 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark61(T61*o){
se_gc_check_id(o,61);
{
if(((gc61*)o)->header.flag==FSOH_UNMARKED){
((gc61*)o)->header.flag=FSOH_MARKED;
/*i3p*/if(NULL!=o->_auteur)gc_mark7((T7*)(o->_auteur));
/*i3p*/if(NULL!=o->_titre)gc_mark7((T7*)(o->_titre));
}
}
}/*--*/

void gc_align_mark61(fsoc*c,gc61*p){
gc61*b=((gc61*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store61)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T61*o=(&(p->object));
((gc61*)o)->header.flag=FSOH_MARKED;
/*i3p*/if(NULL!=o->_auteur)gc_mark7((T7*)(o->_auteur));
/*i3p*/if(NULL!=o->_titre)gc_mark7((T7*)(o->_titre));
}
}
}/*--*/
fsoc H61={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark61,
(void(*)(mch*))gc_sweep61},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc61))-1)};

T61*new61(void){
gc61*n;
fsoc*c;
if(store_left61>1){
store_left61--;
n=store61++;
}
else if(gc_free61!=NULL){
n=gc_free61;
gc_free61=n->header.next;
}
else if(store_left61==1){
store_left61=0;
store_chunk61->header.state_type=FSO_USED_CHUNK;
n=store61++;
}
else{
c=gc_fsoc_get1();
if(gc_free61!=NULL){
n=gc_free61;
gc_free61=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk61=c;
*store_chunk61=H61;
store61=((gc61*)(&(store_chunk61->first_object)));
store_left61=H61.count_minus_one;
n=store61++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M61;
return((T61*)n);
}/*--*/

void gc_sweep60(fsoc*c){
gc60*o1,*o2;
o1=((gc60*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store60;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free60;
gc_free60=o1;
}
}
}
else{
int dead=1;
gc60* old_gc_free = gc_free60;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free60;
gc_free60=o1;
}
}
if (dead){
gc_free60 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark60(T60*o){
se_gc_check_id(o,60);
{
if(((gc60*)o)->header.flag==FSOH_UNMARKED){
((gc60*)o)->header.flag=FSOH_MARKED;
/*i6p*/if(NULL!=o->_realisateur)gc_mark7((T7*)(o->_realisateur));
/*i6p*/if(NULL!=o->_liste_acteurs)gc_mark131((T131*)(o->_liste_acteurs));
/*i6p*/if(NULL!=o->_type)gc_mark7((T7*)(o->_type));
/*i6p*/if(NULL!=o->_titre)gc_mark7((T7*)(o->_titre));
}
}
}/*--*/

void gc_align_mark60(fsoc*c,gc60*p){
gc60*b=((gc60*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store60)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T60*o=(&(p->object));
((gc60*)o)->header.flag=FSOH_MARKED;
/*i6p*/if(NULL!=o->_realisateur)gc_mark7((T7*)(o->_realisateur));
/*i6p*/if(NULL!=o->_liste_acteurs)gc_mark131((T131*)(o->_liste_acteurs));
/*i6p*/if(NULL!=o->_type)gc_mark7((T7*)(o->_type));
/*i6p*/if(NULL!=o->_titre)gc_mark7((T7*)(o->_titre));
}
}
}/*--*/
fsoc H60={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark60,
(void(*)(mch*))gc_sweep60},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc60))-1)};

T60*new60(void){
gc60*n;
fsoc*c;
if(store_left60>1){
store_left60--;
n=store60++;
}
else if(gc_free60!=NULL){
n=gc_free60;
gc_free60=n->header.next;
}
else if(store_left60==1){
store_left60=0;
store_chunk60->header.state_type=FSO_USED_CHUNK;
n=store60++;
}
else{
c=gc_fsoc_get1();
if(gc_free60!=NULL){
n=gc_free60;
gc_free60=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk60=c;
*store_chunk60=H60;
store60=((gc60*)(&(store_chunk60->first_object)));
store_left60=H60.count_minus_one;
n=store60++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M60;
return((T60*)n);
}/*--*/

void gc_sweep59(fsoc*c){
gc59*o1,*o2;
o1=((gc59*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store59;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free59;
gc_free59=o1;
}
}
}
else{
int dead=1;
gc59* old_gc_free = gc_free59;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free59;
gc_free59=o1;
}
}
if (dead){
gc_free59 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark59(T59*o){
se_gc_check_id(o,59);
{
if(((gc59*)o)->header.flag==FSOH_UNMARKED){
((gc59*)o)->header.flag=FSOH_MARKED;
/*i5p*/if(NULL!=o->_motdepasse)gc_mark7((T7*)(o->_motdepasse));
/*i5p*/if(NULL!=o->_identifiant)gc_mark7((T7*)(o->_identifiant));
/*i5p*/if(NULL!=o->_prenom)gc_mark7((T7*)(o->_prenom));
/*i5p*/if(NULL!=o->_nom)gc_mark7((T7*)(o->_nom));
}
}
}/*--*/

void gc_align_mark59(fsoc*c,gc59*p){
gc59*b=((gc59*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store59)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T59*o=(&(p->object));
((gc59*)o)->header.flag=FSOH_MARKED;
/*i5p*/if(NULL!=o->_motdepasse)gc_mark7((T7*)(o->_motdepasse));
/*i5p*/if(NULL!=o->_identifiant)gc_mark7((T7*)(o->_identifiant));
/*i5p*/if(NULL!=o->_prenom)gc_mark7((T7*)(o->_prenom));
/*i5p*/if(NULL!=o->_nom)gc_mark7((T7*)(o->_nom));
}
}
}/*--*/
fsoc H59={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark59,
(void(*)(mch*))gc_sweep59},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc59))-1)};

T59*new59(void){
gc59*n;
fsoc*c;
if(store_left59>1){
store_left59--;
n=store59++;
}
else if(gc_free59!=NULL){
n=gc_free59;
gc_free59=n->header.next;
}
else if(store_left59==1){
store_left59=0;
store_chunk59->header.state_type=FSO_USED_CHUNK;
n=store59++;
}
else{
c=gc_fsoc_get1();
if(gc_free59!=NULL){
n=gc_free59;
gc_free59=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk59=c;
*store_chunk59=H59;
store59=((gc59*)(&(store_chunk59->first_object)));
store_left59=H59.count_minus_one;
n=store59++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M59;
return((T59*)n);
}/*--*/

void gc_sweep131(fsoc*c){
gc131*o1,*o2;
o1=((gc131*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store131;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free131;
gc_free131=o1;
}
}
}
else{
int dead=1;
gc131* old_gc_free = gc_free131;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free131;
gc_free131=o1;
}
}
if (dead){
gc_free131 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark131(T131*o){
se_gc_check_id(o,131);
{
if(((gc131*)o)->header.flag==FSOH_UNMARKED){
((gc131*)o)->header.flag=FSOH_MARKED;
/*i4p*/{
T136 na=o->_storage;
if(gc_find_chunk(na)!=NULL){/* non external NA */
   rsoh*h=((rsoh*)na)-1;
   if((h->header.magic_flag)==RSOH_UNMARKED){
      h->header.magic_flag=RSOH_MARKED;
r131mark_native_arrays(NULL,o);
}
}
}}
}
}/*--*/

void gc_align_mark131(fsoc*c,gc131*p){
gc131*b=((gc131*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store131)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T131*o=(&(p->object));
((gc131*)o)->header.flag=FSOH_MARKED;
/*i4p*/{
T136 na=o->_storage;
if(gc_find_chunk(na)!=NULL){/* non external NA */
   rsoh*h=((rsoh*)na)-1;
   if((h->header.magic_flag)==RSOH_UNMARKED){
      h->header.magic_flag=RSOH_MARKED;
r131mark_native_arrays(NULL,o);
}
}
}}
}
}/*--*/
fsoc H131={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark131,
(void(*)(mch*))gc_sweep131},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc131))-1)};

T131*new131(void){
gc131*n;
fsoc*c;
if(store_left131>1){
store_left131--;
n=store131++;
}
else if(gc_free131!=NULL){
n=gc_free131;
gc_free131=n->header.next;
}
else if(store_left131==1){
store_left131=0;
store_chunk131->header.state_type=FSO_USED_CHUNK;
n=store131++;
}
else{
c=gc_fsoc_get1();
if(gc_free131!=NULL){
n=gc_free131;
gc_free131=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk131=c;
*store_chunk131=H131;
store131=((gc131*)(&(store_chunk131->first_object)));
store_left131=H131.count_minus_one;
n=store131++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M131;
return((T131*)n);
}/*--*/

void gc_sweep62(fsoc*c){
gc62*o1,*o2;
o1=((gc62*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store62;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free62;
gc_free62=o1;
}
}
}
else{
int dead=1;
gc62* old_gc_free = gc_free62;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free62;
gc_free62=o1;
}
}
if (dead){
gc_free62 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark62(T62*o){
se_gc_check_id(o,62);
{
if(((gc62*)o)->header.flag==FSOH_UNMARKED){
((gc62*)o)->header.flag=FSOH_MARKED;
/*i10p*/if(NULL!=o->_buffer)gc_mark9((o->_buffer));
/*i10p*/if(NULL!=o->_path)gc_mark7((T7*)(o->_path));
}
}
}/*--*/

void gc_align_mark62(fsoc*c,gc62*p){
gc62*b=((gc62*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store62)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T62*o=(&(p->object));
((gc62*)o)->header.flag=FSOH_MARKED;
/*i10p*/if(NULL!=o->_buffer)gc_mark9((o->_buffer));
/*i10p*/if(NULL!=o->_path)gc_mark7((T7*)(o->_path));
}
}
}/*--*/
fsoc H62={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark62,
(void(*)(mch*))gc_sweep62},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc62))-1)};

T62*new62(void){
gc62*n;
fsoc*c;
if(store_left62>1){
store_left62--;
n=store62++;
}
else if(gc_free62!=NULL){
n=gc_free62;
gc_free62=n->header.next;
}
else if(store_left62==1){
store_left62=0;
store_chunk62->header.state_type=FSO_USED_CHUNK;
n=store62++;
}
else{
c=gc_fsoc_get1();
if(gc_free62!=NULL){
n=gc_free62;
gc_free62=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk62=c;
*store_chunk62=H62;
store62=((gc62*)(&(store_chunk62->first_object)));
store_left62=H62.count_minus_one;
n=store62++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M62;
return((T62*)n);
}/*--*/

void gc_sweep130(fsoc*c){
gc130*o1,*o2;
o1=((gc130*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store130;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free130;
gc_free130=o1;
}
}
}
else{
int dead=1;
gc130* old_gc_free = gc_free130;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free130;
gc_free130=o1;
}
}
if (dead){
gc_free130 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark130(T130*o){
se_gc_check_id(o,130);
{
if(((gc130*)o)->header.flag==FSOH_UNMARKED){
((gc130*)o)->header.flag=FSOH_MARKED;
/*i4p*/{
T135 na=o->_storage;
if(gc_find_chunk(na)!=NULL){/* non external NA */
   rsoh*h=((rsoh*)na)-1;
   if((h->header.magic_flag)==RSOH_UNMARKED){
      h->header.magic_flag=RSOH_MARKED;
r130mark_native_arrays(NULL,o);
}
}
}}
}
}/*--*/

void gc_align_mark130(fsoc*c,gc130*p){
gc130*b=((gc130*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store130)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T130*o=(&(p->object));
((gc130*)o)->header.flag=FSOH_MARKED;
/*i4p*/{
T135 na=o->_storage;
if(gc_find_chunk(na)!=NULL){/* non external NA */
   rsoh*h=((rsoh*)na)-1;
   if((h->header.magic_flag)==RSOH_UNMARKED){
      h->header.magic_flag=RSOH_MARKED;
r130mark_native_arrays(NULL,o);
}
}
}}
}
}/*--*/
fsoc H130={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark130,
(void(*)(mch*))gc_sweep130},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc130))-1)};

T130*new130(void){
gc130*n;
fsoc*c;
if(store_left130>1){
store_left130--;
n=store130++;
}
else if(gc_free130!=NULL){
n=gc_free130;
gc_free130=n->header.next;
}
else if(store_left130==1){
store_left130=0;
store_chunk130->header.state_type=FSO_USED_CHUNK;
n=store130++;
}
else{
c=gc_fsoc_get1();
if(gc_free130!=NULL){
n=gc_free130;
gc_free130=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk130=c;
*store_chunk130=H130;
store130=((gc130*)(&(store_chunk130->first_object)));
store_left130=H130.count_minus_one;
n=store130++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M130;
return((T130*)n);
}/*--*/

void gc_sweep54(fsoc*c){
gc54*o1,*o2;
o1=((gc54*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store54;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free54;
gc_free54=o1;
}
}
}
else{
int dead=1;
gc54* old_gc_free = gc_free54;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free54;
gc_free54=o1;
}
}
if (dead){
gc_free54 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark54(T54*o){
se_gc_check_id(o,54);
{
if(((gc54*)o)->header.flag==FSOH_UNMARKED){
((gc54*)o)->header.flag=FSOH_MARKED;
/*i5p*/if(NULL!=o->_motdepasse)gc_mark7((T7*)(o->_motdepasse));
/*i5p*/if(NULL!=o->_identifiant)gc_mark7((T7*)(o->_identifiant));
/*i5p*/if(NULL!=o->_prenom)gc_mark7((T7*)(o->_prenom));
/*i5p*/if(NULL!=o->_nom)gc_mark7((T7*)(o->_nom));
}
}
}/*--*/

void gc_align_mark54(fsoc*c,gc54*p){
gc54*b=((gc54*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store54)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T54*o=(&(p->object));
((gc54*)o)->header.flag=FSOH_MARKED;
/*i5p*/if(NULL!=o->_motdepasse)gc_mark7((T7*)(o->_motdepasse));
/*i5p*/if(NULL!=o->_identifiant)gc_mark7((T7*)(o->_identifiant));
/*i5p*/if(NULL!=o->_prenom)gc_mark7((T7*)(o->_prenom));
/*i5p*/if(NULL!=o->_nom)gc_mark7((T7*)(o->_nom));
}
}
}/*--*/
fsoc H54={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark54,
(void(*)(mch*))gc_sweep54},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc54))-1)};

T54*new54(void){
gc54*n;
fsoc*c;
if(store_left54>1){
store_left54--;
n=store54++;
}
else if(gc_free54!=NULL){
n=gc_free54;
gc_free54=n->header.next;
}
else if(store_left54==1){
store_left54=0;
store_chunk54->header.state_type=FSO_USED_CHUNK;
n=store54++;
}
else{
c=gc_fsoc_get1();
if(gc_free54!=NULL){
n=gc_free54;
gc_free54=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk54=c;
*store_chunk54=H54;
store54=((gc54*)(&(store_chunk54->first_object)));
store_left54=H54.count_minus_one;
n=store54++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M54;
return((T54*)n);
}/*--*/

void gc_sweep129(fsoc*c){
gc129*o1,*o2;
o1=((gc129*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store129;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free129;
gc_free129=o1;
}
}
}
else{
int dead=1;
gc129* old_gc_free = gc_free129;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free129;
gc_free129=o1;
}
}
if (dead){
gc_free129 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark129(T129*o){
se_gc_check_id(o,129);
{
if(((gc129*)o)->header.flag==FSOH_UNMARKED){
((gc129*)o)->header.flag=FSOH_MARKED;
/*i4p*/{
T134 na=o->_storage;
if(gc_find_chunk(na)!=NULL){/* non external NA */
   rsoh*h=((rsoh*)na)-1;
   if((h->header.magic_flag)==RSOH_UNMARKED){
      h->header.magic_flag=RSOH_MARKED;
r129mark_native_arrays(NULL,o);
}
}
}}
}
}/*--*/

void gc_align_mark129(fsoc*c,gc129*p){
gc129*b=((gc129*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store129)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T129*o=(&(p->object));
((gc129*)o)->header.flag=FSOH_MARKED;
/*i4p*/{
T134 na=o->_storage;
if(gc_find_chunk(na)!=NULL){/* non external NA */
   rsoh*h=((rsoh*)na)-1;
   if((h->header.magic_flag)==RSOH_UNMARKED){
      h->header.magic_flag=RSOH_MARKED;
r129mark_native_arrays(NULL,o);
}
}
}}
}
}/*--*/
fsoc H129={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark129,
(void(*)(mch*))gc_sweep129},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc129))-1)};

T129*new129(void){
gc129*n;
fsoc*c;
if(store_left129>1){
store_left129--;
n=store129++;
}
else if(gc_free129!=NULL){
n=gc_free129;
gc_free129=n->header.next;
}
else if(store_left129==1){
store_left129=0;
store_chunk129->header.state_type=FSO_USED_CHUNK;
n=store129++;
}
else{
c=gc_fsoc_get1();
if(gc_free129!=NULL){
n=gc_free129;
gc_free129=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk129=c;
*store_chunk129=H129;
store129=((gc129*)(&(store_chunk129->first_object)));
store_left129=H129.count_minus_one;
n=store129++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M129;
return((T129*)n);
}/*--*/

void gc_sweep55(fsoc*c){
gc55*o1,*o2;
o1=((gc55*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store55;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free55;
gc_free55=o1;
}
}
}
else{
int dead=1;
gc55* old_gc_free = gc_free55;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free55;
gc_free55=o1;
}
}
if (dead){
gc_free55 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark55(T55*o){
se_gc_check_id(o,55);
{
if(((gc55*)o)->header.flag==FSOH_UNMARKED){
((gc55*)o)->header.flag=FSOH_MARKED;
/*i5p*/if(NULL!=o->_media)Xgc_mark49((T0*)(o->_media));
/*i5p*/if(NULL!=o->_utilisateur)Xgc_mark54((T0*)(o->_utilisateur));
}
}
}/*--*/

void gc_align_mark55(fsoc*c,gc55*p){
gc55*b=((gc55*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store55)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T55*o=(&(p->object));
((gc55*)o)->header.flag=FSOH_MARKED;
/*i5p*/if(NULL!=o->_media)Xgc_mark49((T0*)(o->_media));
/*i5p*/if(NULL!=o->_utilisateur)Xgc_mark54((T0*)(o->_utilisateur));
}
}
}/*--*/
fsoc H55={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark55,
(void(*)(mch*))gc_sweep55},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc55))-1)};

T55*new55(void){
gc55*n;
fsoc*c;
if(store_left55>1){
store_left55--;
n=store55++;
}
else if(gc_free55!=NULL){
n=gc_free55;
gc_free55=n->header.next;
}
else if(store_left55==1){
store_left55=0;
store_chunk55->header.state_type=FSO_USED_CHUNK;
n=store55++;
}
else{
c=gc_fsoc_get1();
if(gc_free55!=NULL){
n=gc_free55;
gc_free55=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk55=c;
*store_chunk55=H55;
store55=((gc55*)(&(store_chunk55->first_object)));
store_left55=H55.count_minus_one;
n=store55++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M55;
return((T55*)n);
}/*--*/

void gc_sweep128(fsoc*c){
gc128*o1,*o2;
o1=((gc128*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store128;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free128;
gc_free128=o1;
}
}
}
else{
int dead=1;
gc128* old_gc_free = gc_free128;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free128;
gc_free128=o1;
}
}
if (dead){
gc_free128 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark128(T128*o){
se_gc_check_id(o,128);
{
if(((gc128*)o)->header.flag==FSOH_UNMARKED){
((gc128*)o)->header.flag=FSOH_MARKED;
/*i4p*/{
T133 na=o->_storage;
if(gc_find_chunk(na)!=NULL){/* non external NA */
   rsoh*h=((rsoh*)na)-1;
   if((h->header.magic_flag)==RSOH_UNMARKED){
      h->header.magic_flag=RSOH_MARKED;
r128mark_native_arrays(NULL,o);
}
}
}}
}
}/*--*/

void gc_align_mark128(fsoc*c,gc128*p){
gc128*b=((gc128*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store128)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T128*o=(&(p->object));
((gc128*)o)->header.flag=FSOH_MARKED;
/*i4p*/{
T133 na=o->_storage;
if(gc_find_chunk(na)!=NULL){/* non external NA */
   rsoh*h=((rsoh*)na)-1;
   if((h->header.magic_flag)==RSOH_UNMARKED){
      h->header.magic_flag=RSOH_MARKED;
r128mark_native_arrays(NULL,o);
}
}
}}
}
}/*--*/
fsoc H128={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark128,
(void(*)(mch*))gc_sweep128},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc128))-1)};

T128*new128(void){
gc128*n;
fsoc*c;
if(store_left128>1){
store_left128--;
n=store128++;
}
else if(gc_free128!=NULL){
n=gc_free128;
gc_free128=n->header.next;
}
else if(store_left128==1){
store_left128=0;
store_chunk128->header.state_type=FSO_USED_CHUNK;
n=store128++;
}
else{
c=gc_fsoc_get1();
if(gc_free128!=NULL){
n=gc_free128;
gc_free128=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk128=c;
*store_chunk128=H128;
store128=((gc128*)(&(store_chunk128->first_object)));
store_left128=H128.count_minus_one;
n=store128++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M128;
return((T128*)n);
}/*--*/

void gc_sweep40(fsoc*c){
gc40*o1,*o2;
o1=((gc40*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store40;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free40;
gc_free40=o1;
}
}
}
else{
int dead=1;
gc40* old_gc_free = gc_free40;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free40;
gc_free40=o1;
}
}
if (dead){
gc_free40 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark40(T40*o){
se_gc_check_id(o,40);
{
if(((gc40*)o)->header.flag==FSOH_UNMARKED){
((gc40*)o)->header.flag=FSOH_MARKED;
/*i3p*/}
}
}/*--*/

void gc_align_mark40(fsoc*c,gc40*p){
gc40*b=((gc40*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store40)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T40*o=(&(p->object));
((gc40*)o)->header.flag=FSOH_MARKED;
/*i3p*/}
}
}/*--*/
fsoc H40={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark40,
(void(*)(mch*))gc_sweep40},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc40))-1)};

T40*new40(void){
gc40*n;
fsoc*c;
if(store_left40>1){
store_left40--;
n=store40++;
}
else if(gc_free40!=NULL){
n=gc_free40;
gc_free40=n->header.next;
}
else if(store_left40==1){
store_left40=0;
store_chunk40->header.state_type=FSO_USED_CHUNK;
n=store40++;
}
else{
c=gc_fsoc_get1();
if(gc_free40!=NULL){
n=gc_free40;
gc_free40=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk40=c;
*store_chunk40=H40;
store40=((gc40*)(&(store_chunk40->first_object)));
store_left40=H40.count_minus_one;
n=store40++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M40;
return((T40*)n);
}/*--*/

void gc_sweep25(fsoc*c){
gc25*o1,*o2;
o1=((gc25*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store25;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free25;
gc_free25=o1;
}
}
}
else{
int dead=1;
gc25* old_gc_free = gc_free25;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free25;
gc_free25=o1;
}
}
if (dead){
gc_free25 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark25(T25*o){
se_gc_check_id(o,25);
{
if(((gc25*)o)->header.flag==FSOH_UNMARKED){
((gc25*)o)->header.flag=FSOH_MARKED;
/*i5p*/if(NULL!=o->_liste_utilisateurs)gc_mark129((T129*)(o->_liste_utilisateurs));
/*i5p*/if(NULL!=o->_liste_emprunts)gc_mark128((T128*)(o->_liste_emprunts));
/*i5p*/if(NULL!=o->_liste_medias)gc_mark130((T130*)(o->_liste_medias));
}
}
}/*--*/

void gc_align_mark25(fsoc*c,gc25*p){
gc25*b=((gc25*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store25)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T25*o=(&(p->object));
((gc25*)o)->header.flag=FSOH_MARKED;
/*i5p*/if(NULL!=o->_liste_utilisateurs)gc_mark129((T129*)(o->_liste_utilisateurs));
/*i5p*/if(NULL!=o->_liste_emprunts)gc_mark128((T128*)(o->_liste_emprunts));
/*i5p*/if(NULL!=o->_liste_medias)gc_mark130((T130*)(o->_liste_medias));
}
}
}/*--*/
fsoc H25={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark25,
(void(*)(mch*))gc_sweep25},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc25))-1)};

T25*new25(void){
gc25*n;
fsoc*c;
if(store_left25>1){
store_left25--;
n=store25++;
}
else if(gc_free25!=NULL){
n=gc_free25;
gc_free25=n->header.next;
}
else if(store_left25==1){
store_left25=0;
store_chunk25->header.state_type=FSO_USED_CHUNK;
n=store25++;
}
else{
c=gc_fsoc_get1();
if(gc_free25!=NULL){
n=gc_free25;
gc_free25=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk25=c;
*store_chunk25=H25;
store25=((gc25*)(&(store_chunk25->first_object)));
store_left25=H25.count_minus_one;
n=store25++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M25;
return((T25*)n);
}/*--*/

void gc_mark9(T9 o){
if(NULL==gc_find_chunk(o))
return; /* external NA */
(((rsoh*)o)-1)->header.magic_flag=RSOH_MARKED;
}/*--*/

T9 new9(unsigned int size){
size=(size*sizeof(T3))+sizeof(rsoh);
size=((size+(sizeof(double)-1))&~(sizeof(double)-1));
if (size<=(na_env9.store_left)){
rsoh*r=na_env9.store;
na_env9.store_left-=size;
if(na_env9.store_left>sizeof(rsoh)){
r->header.size=size;
na_env9.store=((rsoh*)(((char*)(na_env9.store))+size));
}
else {
r->header.size=size+na_env9.store_left;
na_env9.store_left=0;
}
(r->header.magic_flag)=RSOH_UNMARKED;
((void)memset((r+1),0,r->header.size-sizeof(rsoh)));
return((T9)(r+1));
}
return((T9)new_na(&na_env9,size));
}/*--*/

void gc_sweep7(fsoc*c){
gc7*o1,*o2;
o1=((gc7*)(&(c->first_object)));
if(c->header.state_type==FSO_STORE_CHUNK){
for(;o1<store7;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
}
else{
o1->header.next=gc_free7;
gc_free7=o1;
}
}
}
else{
int dead=1;
gc7* old_gc_free = gc_free7;
o2=o1+c->count_minus_one;
for(;o1<=o2;o1++){
if((o1->header.flag)==FSOH_MARKED){
o1->header.flag=FSOH_UNMARKED;
dead=0;}
else{
o1->header.next=gc_free7;
gc_free7=o1;
}
}
if (dead){
gc_free7 = old_gc_free;
c->next=fsocfl;
fsocfl=c;
c->header.state_type=FSO_FREE_CHUNK;
}
}
}/*--*/

void gc_mark7(T7*o){
se_gc_check_id(o,7);
{
if(((gc7*)o)->header.flag==FSOH_UNMARKED){
((gc7*)o)->header.flag=FSOH_MARKED;
/*i3p*/if(NULL!=o->_storage)gc_mark9((o->_storage));
}
}
}/*--*/

void gc_align_mark7(fsoc*c,gc7*p){
gc7*b=((gc7*)(&(c->first_object)));
if((c->header.state_type==FSO_STORE_CHUNK)&&(((char*)p)>=((char*)store7)))return;
if(((char*)p)>((char*)(b+(c->count_minus_one))))return;
if(((char*)p)<((char*)b))return;
if(((((char*)p)-((char*)b))%sizeof(*p))==0){
if(p->header.flag==FSOH_UNMARKED){
T7*o=(&(p->object));
((gc7*)o)->header.flag=FSOH_MARKED;
/*i3p*/if(NULL!=o->_storage)gc_mark9((o->_storage));
}
}
}/*--*/
fsoc H7={{FSOC_SIZE,FSO_STORE_CHUNK,
(void(*)(mch*,void*))gc_align_mark7,
(void(*)(mch*))gc_sweep7},NULL,(((FSOC_SIZE-sizeof(fsoc)+sizeof(double))/sizeof(gc7))-1)};

T7*new7(void){
gc7*n;
fsoc*c;
if(store_left7>1){
store_left7--;
n=store7++;
}
else if(gc_free7!=NULL){
n=gc_free7;
gc_free7=n->header.next;
}
else if(store_left7==1){
store_left7=0;
store_chunk7->header.state_type=FSO_USED_CHUNK;
n=store7++;
}
else{
c=gc_fsoc_get1();
if(gc_free7!=NULL){
n=gc_free7;
gc_free7=n->header.next;
}
else{
if(c==NULL)c=gc_fsoc_get2();
store_chunk7=c;
*store_chunk7=H7;
store7=((gc7*)(&(store_chunk7->first_object)));
store_left7=H7.count_minus_one;
n=store7++;
}
}
n->header.flag=FSOH_UNMARKED;
n->object=M7;
return((T7*)n);
}/*--*/

void Xgc_mark54(T0*o){
{int i=o->id;
if (i <= 54) {
gc_mark54((T54*)o);
}
else{
gc_mark59((T59*)o);
}}}/*--*/

void Xgc_mark49(T0*o){
{int i=o->id;
if (i <= 60) {
gc_mark60((T60*)o);
}
else{
gc_mark61((T61*)o);
}}}/*--*/
T25*eiffel_root_object=(void*)0;
int se_argc;
char**se_argv;
T7*g[138];
T7*t[138];
char*p[138];
void(*se_prinT[138])(FILE*,void*);
int se_strucT[138]={0,sizeof(T1),sizeof(T2),sizeof(T3),0,sizeof(T5),sizeof(T6),sizeof(T7),sizeof(T8),sizeof(T9),sizeof(T10),
sizeof(T11),
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
sizeof(T25),
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
sizeof(T40),
0,
0,
0,
0,
0,
0,
sizeof(T47),
sizeof(T48),
0,
0,
0,
0,
0,
sizeof(T54),
sizeof(T55),
0,
0,
sizeof(T58),
sizeof(T59),
sizeof(T60),
sizeof(T61),
sizeof(T62),
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
sizeof(T128),
sizeof(T129),
sizeof(T130),
sizeof(T131),
0,
sizeof(T133),
sizeof(T134),
sizeof(T135),
sizeof(T136),
sizeof(T137)};

void se_atexit(void){
se_frame_descriptor fd={"<atexit wrapper>",0,0,"",1};
se_dump_stack ds;
ds.fd=&fd;
ds.p=0;
ds.caller=NULL;
ds.exception_origin=NULL;
ds.locals=NULL;
r47se_atexit(&ds,NULL/*Unused Target*/);
}/*--*/

void initialize_eiffel_runtime(int argc,char*argv[]){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
se_frame_descriptor irfd={"<runtime init>",0,0,"",1};
se_dump_stack ds = {NULL,NULL,0,NULL,NULL};
ds.fd=&irfd;
set_dump_stack_top(&ds);/*link*/
se_argc=argc;
se_argv=argv;
atexit(se_atexit);
gcmt=((mch**)se_malloc((gcmt_max+1)*sizeof(void*)));
#ifdef FIXED_STACK_BOTTOM
if (!stack_bottom) stack_bottom=((void**)(void*)(&argc));
#endif
p[0]="???";
p[61]="/comptes/E113637T/Documents/M1/Eiffel/Projet/tower/livre.e";
p[54]="/comptes/E113637T/Documents/M1/Eiffel/Projet/tower/utilisateur.e";
p[59]="/comptes/E113637T/Documents/M1/Eiffel/Projet/tower/administrateur.e";
p[60]="/comptes/E113637T/Documents/M1/Eiffel/Projet/tower/dvd.e";
p[25]="/comptes/E113637T/Documents/M1/Eiffel/Projet/tower/mediatheque.e";
p[55]="/comptes/E113637T/Documents/M1/Eiffel/Projet/tower/emprunt.e";
p[49]="/comptes/E113637T/Documents/M1/Eiffel/Projet/tower/media.e";
p[106]="/usr/local/opt/SmartEiffel/lib/kernel/procedure.e";
p[101]="/usr/local/opt/SmartEiffel/lib/kernel/memory.e";
p[15]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[16]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[75]="/usr/local/opt/SmartEiffel/lib/kernel/routine.e";
p[17]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[18]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[19]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[20]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[21]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[22]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[23]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[14]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[24]="/usr/local/opt/SmartEiffel/lib/kernel/tuple.e";
p[8]="/usr/local/opt/SmartEiffel/lib/kernel/pointer.e";
p[82]="/usr/local/opt/SmartEiffel/lib/kernel/reference.e";
p[74]="/usr/local/opt/SmartEiffel/lib/kernel/function.e";
p[6]="/usr/local/opt/SmartEiffel/lib/kernel/boolean.e";
p[66]="/usr/local/opt/SmartEiffel/lib/kernel/safe_equal.e";
p[13]="/usr/local/opt/SmartEiffel/lib/kernel/any.e";
p[107]="/usr/local/opt/SmartEiffel/lib/kernel/weak_reference.e";
p[36]="/usr/local/opt/SmartEiffel/lib/kernel/platform.e";
p[80]="/usr/local/opt/SmartEiffel/lib/kernel/internal/internals_handler.e";
p[94]="/usr/local/opt/SmartEiffel/lib/kernel/internal/native_array_internals.e";
p[45]="/usr/local/opt/SmartEiffel/lib/kernel/internal/typed_internals.e";
p[52]="/usr/local/opt/SmartEiffel/lib/kernel/internal/native_array_collector.e";
p[46]="/usr/local/opt/SmartEiffel/lib/kernel/internal/internals.e";
p[51]="/usr/local/opt/SmartEiffel/lib/storage/collection.e";
p[90]="/usr/local/opt/SmartEiffel/lib/storage/collection/fast_array.e";
p[50]="/usr/local/opt/SmartEiffel/lib/storage/collection/array.e";
p[108]="/usr/local/opt/SmartEiffel/lib/storage/collection/ring_array.e";
p[65]="/usr/local/opt/SmartEiffel/lib/storage/low_level/native_array.e";
p[100]="/usr/local/opt/SmartEiffel/lib/storage/low_level/recycling_pool.e";
p[53]="/usr/local/opt/SmartEiffel/lib/storage/internal/arrayed_collection.e";
p[112]="/usr/local/opt/SmartEiffel/lib/io/directory_notation.e";
p[64]="/usr/local/opt/SmartEiffel/lib/io/filter.e";
p[26]="/usr/local/opt/SmartEiffel/lib/io/output_stream.e";
p[119]="/usr/local/opt/SmartEiffel/lib/io/path_name.e";
p[78]="/usr/local/opt/SmartEiffel/lib/io/filter_input_stream.e";
p[38]="/usr/local/opt/SmartEiffel/lib/io/terminal_output_stream.e";
p[110]="/usr/local/opt/SmartEiffel/lib/io/file_tools.e";
p[42]="/usr/local/opt/SmartEiffel/lib/io/terminal_input_stream.e";
p[41]="/usr/local/opt/SmartEiffel/lib/io/terminal_input_output_stream.e";
p[70]="/usr/local/opt/SmartEiffel/lib/io/filter_output_stream.e";
p[43]="/usr/local/opt/SmartEiffel/lib/io/input_stream.e";
p[27]="/usr/local/opt/SmartEiffel/lib/io/stream.e";
p[63]="/usr/local/opt/SmartEiffel/lib/io/terminal/file.e";
p[62]="/usr/local/opt/SmartEiffel/lib/io/terminal/text_file_read.e";
p[40]="/usr/local/opt/SmartEiffel/lib/io/terminal/std_input_output.e";
p[37]="/usr/local/opt/SmartEiffel/lib/io/terminal/std_error.e";
p[48]="/usr/local/opt/SmartEiffel/lib/io/terminal/std_input.e";
p[47]="/usr/local/opt/SmartEiffel/lib/io/terminal/std_output.e";
p[44]="/usr/local/opt/SmartEiffel/lib/io/low_level/input_stream_tools.e";
p[30]="/usr/local/opt/SmartEiffel/lib/io/low_level/output_stream_tools.e";
p[39]="/usr/local/opt/SmartEiffel/lib/io/low_level/redirection_tools.e";
p[111]="/usr/local/opt/SmartEiffel/lib/io/low_level/basic_directory.e";
p[121]="/usr/local/opt/SmartEiffel/lib/io/internal/unixish_path_name.e";
p[29]="/usr/local/opt/SmartEiffel/lib/io/internal/filterable.e";
p[118]="/usr/local/opt/SmartEiffel/lib/io/internal/path_joiner.e";
p[120]="/usr/local/opt/SmartEiffel/lib/io/path_name/posix_path_name.e";
p[117]="/usr/local/opt/SmartEiffel/lib/io/path_name/path_name_notation.e";
p[115]="/usr/local/opt/SmartEiffel/lib/io/path_name/macintosh_directory_notation.e";
p[123]="/usr/local/opt/SmartEiffel/lib/io/path_name/openvms_directory_notation.e";
p[126]="/usr/local/opt/SmartEiffel/lib/io/path_name/microsoft_path_name.e";
p[125]="/usr/local/opt/SmartEiffel/lib/io/path_name/windows_directory_notation.e";
p[116]="/usr/local/opt/SmartEiffel/lib/io/path_name/unix_directory_notation.e";
p[124]="/usr/local/opt/SmartEiffel/lib/io/path_name/amiga_directory_notation.e";
p[127]="/usr/local/opt/SmartEiffel/lib/io/path_name/cygwin_directory_notation.e";
p[114]="/usr/local/opt/SmartEiffel/lib/unicode/unicode_string_handler.e";
p[73]="/usr/local/opt/SmartEiffel/lib/iterator/iterator.e";
p[81]="/usr/local/opt/SmartEiffel/lib/iterator/internal/iterator_on_traversable.e";
p[91]="/usr/local/opt/SmartEiffel/lib/iterator/internal/iterator_on_unicode_string.e";
p[77]="/usr/local/opt/SmartEiffel/lib/iterator/internal/iterator_on_string.e";
p[93]="/usr/local/opt/SmartEiffel/lib/misc/mini_parser_buffer.e";
p[92]="/usr/local/opt/SmartEiffel/lib/sequencer/events_set.e";
p[71]="/usr/local/opt/SmartEiffel/lib/sequencer/event_descriptor.e";
p[79]="/usr/local/opt/SmartEiffel/lib/sequencer/events/can_read_data_from_stream.e";
p[105]="/usr/local/opt/SmartEiffel/lib/sequencer/events/network_connection_occurred.e";
p[72]="/usr/local/opt/SmartEiffel/lib/sequencer/events/can_write_data_to_stream.e";
p[28]="/usr/local/opt/SmartEiffel/lib/abilities/recyclable.e";
p[99]="/usr/local/opt/SmartEiffel/lib/abilities/disposable.e";
p[32]="/usr/local/opt/SmartEiffel/lib/abilities/traversable.e";
p[35]="/usr/local/opt/SmartEiffel/lib/abilities/hashable.e";
p[33]="/usr/local/opt/SmartEiffel/lib/abilities/storable.e";
p[34]="/usr/local/opt/SmartEiffel/lib/abilities/comparable.e";
p[12]="/usr/local/opt/SmartEiffel/lib/numeric/real_extended.e";
p[67]="/usr/local/opt/SmartEiffel/lib/numeric/real_general.e";
p[2]="/usr/local/opt/SmartEiffel/lib/numeric/integer_32.e";
p[68]="/usr/local/opt/SmartEiffel/lib/numeric/number.e";
p[4]="/usr/local/opt/SmartEiffel/lib/numeric/real_32.e";
p[1]="/usr/local/opt/SmartEiffel/lib/numeric/integer_8.e";
p[86]="/usr/local/opt/SmartEiffel/lib/numeric/mutable_big_integer.e";
p[11]="/usr/local/opt/SmartEiffel/lib/numeric/integer_64.e";
p[76]="/usr/local/opt/SmartEiffel/lib/numeric/number_tools.e";
p[56]="/usr/local/opt/SmartEiffel/lib/numeric/integer_general.e";
p[5]="/usr/local/opt/SmartEiffel/lib/numeric/real_64.e";
p[57]="/usr/local/opt/SmartEiffel/lib/numeric/numeric.e";
p[10]="/usr/local/opt/SmartEiffel/lib/numeric/integer_16.e";
p[87]="/usr/local/opt/SmartEiffel/lib/numeric/internal/fraction_with_big_integer_number.e";
p[84]="/usr/local/opt/SmartEiffel/lib/numeric/internal/integer_64_number.e";
p[85]="/usr/local/opt/SmartEiffel/lib/numeric/internal/integer_general_number.e";
p[88]="/usr/local/opt/SmartEiffel/lib/numeric/internal/fraction_general_number.e";
p[89]="/usr/local/opt/SmartEiffel/lib/numeric/internal/big_integer_number.e";
p[69]="/usr/local/opt/SmartEiffel/lib/string/unicode_string.e";
p[3]="/usr/local/opt/SmartEiffel/lib/string/character.e";
p[7]="/usr/local/opt/SmartEiffel/lib/string/string.e";
p[31]="/usr/local/opt/SmartEiffel/lib/string/low_level/string_handler.e";
p[113]="/usr/local/opt/SmartEiffel/lib/time/time_formatter.e";
p[58]="/usr/local/opt/SmartEiffel/lib/time/time.e";
p[83]="/usr/local/opt/SmartEiffel/lib/time/microsecond_time.e";
p[102]="/usr/local/opt/SmartEiffel/lib/net/access.e";
p[104]="/usr/local/opt/SmartEiffel/lib/net/socket_input_output_stream.e";
p[95]="/usr/local/opt/SmartEiffel/lib/net/low_level/socket_server.e";
p[109]="/usr/local/opt/SmartEiffel/lib/net/low_level/client_socket_input_output_stream.e";
p[103]="/usr/local/opt/SmartEiffel/lib/net/low_level/server_socket_input_output_stream.e";
p[96]="/usr/local/opt/SmartEiffel/lib/net/low_level/socket_plug_in.e";
p[97]="/usr/local/opt/SmartEiffel/lib/net/low_level/socket_handler.e";
p[98]="/usr/local/opt/SmartEiffel/lib/net/low_level/socket.e";
p[122]="/usr/local/opt/SmartEiffel/lib/exec/system.e";
se_prinT[137]=((void(*)(FILE*,void*))se_prinT137);
p[137]=p[82];
se_prinT[136]=((void(*)(FILE*,void*))se_prinT136);
p[136]=p[65];
se_prinT[135]=((void(*)(FILE*,void*))se_prinT135);
p[135]=p[65];
se_prinT[134]=((void(*)(FILE*,void*))se_prinT134);
p[134]=p[65];
se_prinT[133]=((void(*)(FILE*,void*))se_prinT133);
p[133]=p[65];
se_prinT[131]=((void(*)(FILE*,void*))se_prinT131);
p[131]=p[50];
se_prinT[130]=((void(*)(FILE*,void*))se_prinT130);
p[130]=p[50];
se_prinT[129]=((void(*)(FILE*,void*))se_prinT129);
p[129]=p[50];
se_prinT[128]=((void(*)(FILE*,void*))se_prinT128);
p[128]=p[50];
se_prinT[62]=((void(*)(FILE*,void*))se_prinT62);
se_prinT[61]=((void(*)(FILE*,void*))se_prinT61);
se_prinT[60]=((void(*)(FILE*,void*))se_prinT60);
se_prinT[59]=((void(*)(FILE*,void*))se_prinT59);
se_prinT[58]=((void(*)(FILE*,void*))se_prinT58);
se_prinT[55]=((void(*)(FILE*,void*))se_prinT55);
se_prinT[54]=((void(*)(FILE*,void*))se_prinT54);
se_prinT[48]=((void(*)(FILE*,void*))se_prinT48);
se_prinT[47]=((void(*)(FILE*,void*))se_prinT47);
se_prinT[40]=((void(*)(FILE*,void*))se_prinT40);
se_prinT[25]=((void(*)(FILE*,void*))se_prinT25);
se_prinT[11]=((void(*)(FILE*,void*))se_prinT11);
se_prinT[10]=((void(*)(FILE*,void*))se_prinT10);
se_prinT[9]=((void(*)(FILE*,void*))se_prinT9);
p[9]=p[65];
se_prinT[8]=((void(*)(FILE*,void*))se_prinT8);
se_prinT[7]=((void(*)(FILE*,void*))se_prinT7);
se_prinT[6]=((void(*)(FILE*,void*))se_prinT6);
se_prinT[5]=((void(*)(FILE*,void*))se_prinT5);
se_prinT[3]=((void(*)(FILE*,void*))se_prinT3);
se_prinT[2]=((void(*)(FILE*,void*))se_prinT2);
se_prinT[1]=((void(*)(FILE*,void*))se_prinT1);
g[61]=(T7*)se_string("LIVRE");
g[54]=(T7*)se_string("UTILISATEUR");
g[59]=(T7*)se_string("ADMINISTRATEUR");
g[60]=(T7*)se_string("DVD");
g[25]=(T7*)se_string("MEDIATHEQUE");
g[55]=(T7*)se_string("EMPRUNT");
g[49]=(T7*)se_string("MEDIA");
g[106]=(T7*)se_string("PROCEDURE");
g[101]=(T7*)se_string("MEMORY");
g[15]=(T7*)se_string("TUPLE 1");
g[16]=(T7*)se_string("TUPLE 2");
g[75]=(T7*)se_string("ROUTINE");
g[17]=(T7*)se_string("TUPLE 3");
g[18]=(T7*)se_string("TUPLE 4");
g[19]=(T7*)se_string("TUPLE 5");
g[20]=(T7*)se_string("TUPLE 6");
g[21]=(T7*)se_string("TUPLE 7");
g[22]=(T7*)se_string("TUPLE 8");
g[23]=(T7*)se_string("TUPLE 9");
g[14]=(T7*)se_string("TUPLE");
g[24]=(T7*)se_string("TUPLE 10");
g[8]=(T7*)se_string("POINTER");
g[82]=(T7*)se_string("REFERENCE");
g[74]=(T7*)se_string("FUNCTION");
g[6]=(T7*)se_string("BOOLEAN");
g[66]=(T7*)se_string("SAFE_EQUAL");
g[13]=(T7*)se_string("ANY");
g[107]=(T7*)se_string("WEAK_REFERENCE");
g[36]=(T7*)se_string("PLATFORM");
g[80]=(T7*)se_string("INTERNALS_HANDLER");
g[94]=(T7*)se_string("NATIVE_ARRAY_INTERNALS");
g[45]=(T7*)se_string("TYPED_INTERNALS");
g[52]=(T7*)se_string("NATIVE_ARRAY_COLLECTOR");
g[46]=(T7*)se_string("INTERNALS");
g[51]=(T7*)se_string("COLLECTION");
g[90]=(T7*)se_string("FAST_ARRAY");
g[50]=(T7*)se_string("ARRAY");
g[108]=(T7*)se_string("RING_ARRAY");
g[65]=(T7*)se_string("NATIVE_ARRAY");
g[100]=(T7*)se_string("RECYCLING_POOL");
g[53]=(T7*)se_string("ARRAYED_COLLECTION");
g[112]=(T7*)se_string("DIRECTORY_NOTATION");
g[64]=(T7*)se_string("FILTER");
g[26]=(T7*)se_string("OUTPUT_STREAM");
g[119]=(T7*)se_string("PATH_NAME");
g[78]=(T7*)se_string("FILTER_INPUT_STREAM");
g[38]=(T7*)se_string("TERMINAL_OUTPUT_STREAM");
g[110]=(T7*)se_string("FILE_TOOLS");
g[42]=(T7*)se_string("TERMINAL_INPUT_STREAM");
g[41]=(T7*)se_string("TERMINAL_INPUT_OUTPUT_STREAM");
g[70]=(T7*)se_string("FILTER_OUTPUT_STREAM");
g[43]=(T7*)se_string("INPUT_STREAM");
g[27]=(T7*)se_string("STREAM");
g[63]=(T7*)se_string("FILE");
g[62]=(T7*)se_string("TEXT_FILE_READ");
g[40]=(T7*)se_string("STD_INPUT_OUTPUT");
g[37]=(T7*)se_string("STD_ERROR");
g[48]=(T7*)se_string("STD_INPUT");
g[47]=(T7*)se_string("STD_OUTPUT");
g[44]=(T7*)se_string("INPUT_STREAM_TOOLS");
g[30]=(T7*)se_string("OUTPUT_STREAM_TOOLS");
g[39]=(T7*)se_string("REDIRECTION_TOOLS");
g[111]=(T7*)se_string("BASIC_DIRECTORY");
g[121]=(T7*)se_string("UNIXISH_PATH_NAME");
g[29]=(T7*)se_string("FILTERABLE");
g[118]=(T7*)se_string("PATH_JOINER");
g[120]=(T7*)se_string("POSIX_PATH_NAME");
g[117]=(T7*)se_string("PATH_NAME_NOTATION");
g[115]=(T7*)se_string("MACINTOSH_DIRECTORY_NOTATION");
g[123]=(T7*)se_string("OPENVMS_DIRECTORY_NOTATION");
g[126]=(T7*)se_string("MICROSOFT_PATH_NAME");
g[125]=(T7*)se_string("WINDOWS_DIRECTORY_NOTATION");
g[116]=(T7*)se_string("UNIX_DIRECTORY_NOTATION");
g[124]=(T7*)se_string("AMIGA_DIRECTORY_NOTATION");
g[127]=(T7*)se_string("CYGWIN_DIRECTORY_NOTATION");
g[114]=(T7*)se_string("UNICODE_STRING_HANDLER");
g[73]=(T7*)se_string("ITERATOR");
g[81]=(T7*)se_string("ITERATOR_ON_TRAVERSABLE");
g[91]=(T7*)se_string("ITERATOR_ON_UNICODE_STRING");
g[77]=(T7*)se_string("ITERATOR_ON_STRING");
g[93]=(T7*)se_string("MINI_PARSER_BUFFER");
g[92]=(T7*)se_string("EVENTS_SET");
g[71]=(T7*)se_string("EVENT_DESCRIPTOR");
g[79]=(T7*)se_string("CAN_READ_DATA_FROM_STREAM");
g[105]=(T7*)se_string("NETWORK_CONNECTION_OCCURRED");
g[72]=(T7*)se_string("CAN_WRITE_DATA_TO_STREAM");
g[28]=(T7*)se_string("RECYCLABLE");
g[99]=(T7*)se_string("DISPOSABLE");
g[32]=(T7*)se_string("TRAVERSABLE");
g[35]=(T7*)se_string("HASHABLE");
g[33]=(T7*)se_string("STORABLE");
g[34]=(T7*)se_string("COMPARABLE");
g[12]=(T7*)se_string("REAL_EXTENDED");
g[67]=(T7*)se_string("REAL_GENERAL");
g[2]=(T7*)se_string("INTEGER_32");
g[68]=(T7*)se_string("NUMBER");
g[4]=(T7*)se_string("REAL_32");
g[1]=(T7*)se_string("INTEGER_8");
g[86]=(T7*)se_string("MUTABLE_BIG_INTEGER");
g[11]=(T7*)se_string("INTEGER_64");
g[76]=(T7*)se_string("NUMBER_TOOLS");
g[56]=(T7*)se_string("INTEGER_GENERAL");
g[5]=(T7*)se_string("REAL_64");
g[57]=(T7*)se_string("NUMERIC");
g[10]=(T7*)se_string("INTEGER_16");
g[87]=(T7*)se_string("FRACTION_WITH_BIG_INTEGER_NUMBER");
g[84]=(T7*)se_string("INTEGER_64_NUMBER");
g[85]=(T7*)se_string("INTEGER_GENERAL_NUMBER");
g[88]=(T7*)se_string("FRACTION_GENERAL_NUMBER");
g[89]=(T7*)se_string("BIG_INTEGER_NUMBER");
g[69]=(T7*)se_string("UNICODE_STRING");
g[3]=(T7*)se_string("CHARACTER");
g[7]=(T7*)se_string("STRING");
g[31]=(T7*)se_string("STRING_HANDLER");
g[113]=(T7*)se_string("TIME_FORMATTER");
g[58]=(T7*)se_string("TIME");
g[83]=(T7*)se_string("MICROSECOND_TIME");
g[102]=(T7*)se_string("ACCESS");
g[104]=(T7*)se_string("SOCKET_INPUT_OUTPUT_STREAM");
g[95]=(T7*)se_string("SOCKET_SERVER");
g[109]=(T7*)se_string("CLIENT_SOCKET_INPUT_OUTPUT_STREAM");
g[103]=(T7*)se_string("SERVER_SOCKET_INPUT_OUTPUT_STREAM");
g[96]=(T7*)se_string("SOCKET_PLUG_IN");
g[97]=(T7*)se_string("SOCKET_HANDLER");
g[98]=(T7*)se_string("SOCKET");
g[122]=(T7*)se_string("SYSTEM");
g[137]=g[82];
g[136]=g[65];
g[135]=g[65];
g[134]=g[65];
g[133]=g[65];
g[131]=g[50];
g[130]=g[50];
g[129]=g[50];
g[128]=g[50];
g[9]=g[65];
t[137]=(T7*)se_string("REFERENCE[INTEGER_32]");
t[136]=(T7*)se_string("NATIVE_ARRAY[STRING]");
t[135]=(T7*)se_string("NATIVE_ARRAY[MEDIA]");
t[134]=(T7*)se_string("NATIVE_ARRAY[UTILISATEUR]");
t[133]=(T7*)se_string("NATIVE_ARRAY[EMPRUNT]");
t[131]=(T7*)se_string("ARRAY[STRING]");
t[130]=(T7*)se_string("ARRAY[MEDIA]");
t[129]=(T7*)se_string("ARRAY[UTILISATEUR]");
t[128]=(T7*)se_string("ARRAY[EMPRUNT]");
t[62]=g[62];
t[61]=g[61];
t[60]=g[60];
t[59]=g[59];
t[58]=g[58];
t[55]=g[55];
t[54]=g[54];
t[48]=g[48];
t[47]=g[47];
t[40]=g[40];
t[25]=g[25];
t[11]=g[11];
t[10]=g[10];
t[9]=(T7*)se_string("NATIVE_ARRAY[CHARACTER]");
t[8]=g[8];
t[7]=g[7];
t[6]=g[6];
t[5]=g[5];
t[3]=g[3];
t[2]=g[2];
t[1]=g[1];
#ifdef SIGINT
signal(SIGINT,se_signal_handler);
#endif
#ifdef SIGTERM
signal(SIGTERM,se_signal_handler);
#endif
#ifdef SIGQUIT
signal(SIGQUIT,se_signal_handler);
#endif
#ifdef SIGILL
signal(SIGILL,se_signal_handler);
#endif
#ifdef SIGABRT
signal(SIGABRT,se_signal_handler);
#endif
#ifdef SIGFPE
signal(SIGFPE,se_signal_handler);
#endif
#ifdef SIGSEGV
signal(SIGSEGV,se_signal_handler);
#endif
#ifdef SIGBUS
signal(SIGBUS,se_signal_handler);
#endif
#ifdef SIGSYS
signal(SIGSYS,se_signal_handler);
#endif
#ifdef SIGTRAP
signal(SIGTRAP,se_signal_handler);
#endif
#ifdef SIGXCPU
signal(SIGXCPU,se_signal_handler);
#endif
#ifdef SIGXFSZ
signal(SIGXFSZ,se_signal_handler);
#endif
se_msi1();
gc_is_off=0;
tmp0=((T0*)(new25()));
eiffel_root_object=((T25*)tmp0);
set_dump_stack_top((void*)0);/*unlink*/
}/*--*/

int main(int argc,char*argv[]){
/*[INTERNAL_C_LOCAL list*/
T0* tmp0;
/*INTERNAL_C_LOCAL list]*/
se_frame_descriptor root={"<system root>",1,0,"%R25%",1};
se_dump_stack ds;
stack_bottom=((void**)(void*)(&argc));
initialize_eiffel_runtime(argc,argv);
tmp0=((T0*)eiffel_root_object);
ds.fd=&root;
ds.current=((void*)(&tmp0));
ds.p=0x0321150A/*l277c5/mediatheque.e*/;
ds.caller=NULL;
ds.exception_origin=NULL;
ds.locals=NULL;
set_dump_stack_top(&ds);/*link*/
r25make(&ds,((T25*)tmp0));
handle(SE_HANDLE_NORMAL_EXIT, NULL);
set_dump_stack_top(NULL);/*unlink*/
exit(0);
return 0;
}/*--*/

T0* X49io(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {MEDIA}.io",0,0,"",1};
T0* R=(void*)0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 61:R=(r61io(&ds,((T61*)C)));

break;
case 60:R=(r60io(&ds,((T60*)C)));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

T6 X49is_default(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {MEDIA}.is_default",0,0,"",1};
T6 R=0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 61:R=(T6)(r61is_default(&ds,((T61*)C)));

break;
case 60:R=(T6)(r60is_default(&ds,((T60*)C)));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

T0* X49default(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {MEDIA}.default",0,0,"",1};
T0* R=(void*)0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 61:R=(r61default(&ds,((T61*)C)));

break;
case 60:R=(r60default(&ds,((T60*)C)));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

T6 X49est_empruntable(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {MEDIA}.est_empruntable",0,0,"",1};
T6 R=0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 61:R=(T6)(r61est_empruntable(&ds,((T61*)C)));

break;
case 60:R=(T6)(r60est_empruntable(&ds,((T60*)C)));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

T2 X49nombre(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {MEDIA}.nombre",0,0,"",1};
T2 R=0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 61:R=((/*RF2*/(((T61*)C))->_nombre/*i3p*/));

break;
case 60:R=((/*RF2*/(((T60*)C))->_nombre/*i6p*/));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

void X49afficher(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {MEDIA}.afficher",0,0,"",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 61:r61afficher(&ds,((T61*)C));

break;
case 60:r60afficher(&ds,((T60*)C));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
}/*--*/

T0* X49titre(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {MEDIA}.titre",0,0,"",1};
T0* R=(void*)0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 61:R=((/*RF2*/(((T61*)C))->_titre/*i3p*/));

break;
case 60:R=((/*RF2*/(((T60*)C))->_titre/*i6p*/));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

T0* X54io(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.io",0,0,"",1};
T0* R=(void*)0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:R=(r59io(&ds,((T59*)C)));

break;
case 54:R=(r54io(&ds,((T54*)C)));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

T6 X54is_default(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.is_default",0,0,"",1};
T6 R=0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:R=(T6)(r59is_default(&ds,((T59*)C)));

break;
case 54:R=(T6)(r54is_default(&ds,((T54*)C)));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

T0* X54motdepasse(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.motdepasse",0,0,"",1};
T0* R=(void*)0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:R=((/*RF2*/(((T59*)C))->_motdepasse/*i5p*/));

break;
case 54:R=((/*RF2*/(((T54*)C))->_motdepasse/*i5p*/));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

T2 X54get_nb_emprunt(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.get_nb_emprunt",0,0,"",1};
T2 R=0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:R=(r59get_nb_emprunt(&ds,((T59*)C)));

break;
case 54:R=(r54get_nb_emprunt(&ds,((T54*)C)));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

void X54make_empty_utilisateur(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.make_empty_utilisateur",0,0,"",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:r59make_empty_utilisateur(&ds,((T59*)C));

break;
case 54:r54make_empty_utilisateur(&ds,((T54*)C));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
}/*--*/

T0* X54get_nom(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.get_nom",0,0,"",1};
T0* R=(void*)0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:R=(r59get_nom(&ds,((T59*)C)));

break;
case 54:R=(r54get_nom(&ds,((T54*)C)));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

T0* X54identifiant(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.identifiant",0,0,"",1};
T0* R=(void*)0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:R=((/*RF2*/(((T59*)C))->_identifiant/*i5p*/));

break;
case 54:R=((/*RF2*/(((T54*)C))->_identifiant/*i5p*/));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

T0* X54get_identifiant(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.get_identifiant",0,0,"",1};
T0* R=(void*)0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:R=(r59get_identifiant(&ds,((T59*)C)));

break;
case 54:R=(r54get_identifiant(&ds,((T54*)C)));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

T0* X54nom(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.nom",0,0,"",1};
T0* R=(void*)0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:R=((/*RF2*/(((T59*)C))->_nom/*i5p*/));

break;
case 54:R=((/*RF2*/(((T54*)C))->_nom/*i5p*/));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

T0* X54default(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.default",0,0,"",1};
T0* R=(void*)0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:R=(r59default(&ds,((T59*)C)));

break;
case 54:R=(r54default(&ds,((T54*)C)));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

void X54set_prenom(se_dump_stack*caller,se_position position,T0*C,T0* a1){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.set_prenom",0,0,"",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:r59set_prenom(&ds,((T59*)C),a1);

break;
case 54:r54set_prenom(&ds,((T54*)C),a1);

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
}/*--*/

T0* X54get_prenom(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.get_prenom",0,0,"",1};
T0* R=(void*)0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:R=(r59get_prenom(&ds,((T59*)C)));

break;
case 54:R=(r54get_prenom(&ds,((T54*)C)));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

T0* X54prenom(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.prenom",0,0,"",1};
T0* R=(void*)0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:R=((/*RF2*/(((T59*)C))->_prenom/*i5p*/));

break;
case 54:R=((/*RF2*/(((T54*)C))->_prenom/*i5p*/));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

void X54set_identifiant(se_dump_stack*caller,se_position position,T0*C,T0* a1){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.set_identifiant",0,0,"",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:r59set_identifiant(&ds,((T59*)C),a1);

break;
case 54:r54set_identifiant(&ds,((T54*)C),a1);

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
}/*--*/

void X54afficher(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.afficher",0,0,"",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:r59afficher(&ds,((T59*)C));

break;
case 54:r54afficher(&ds,((T54*)C));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
}/*--*/

void X54set_nom(se_dump_stack*caller,se_position position,T0*C,T0* a1){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.set_nom",0,0,"",1};
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:r59set_nom(&ds,((T59*)C),a1);

break;
case 54:r54set_nom(&ds,((T54*)C),a1);

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
}/*--*/

T2 X54nb_emprunt(se_dump_stack*caller,se_position position,T0*C){
static se_frame_descriptor fd={"Dynamic dispatch {UTILISATEUR}.nb_emprunt",0,0,"",1};
T2 R=0;
se_dump_stack ds;
ds.fd=&fd;
ds.current=NULL;
ds.p=(caller->p);
ds.caller=caller;
ds.exception_origin=NULL;
ds.locals=NULL;
{Tid id=vc(C,position)->id;
set_dump_stack_top(&ds);/*link*/
switch(id){
case 59:R=((/*RF2*/(((T59*)C))->_nb_emprunt/*i5p*/));

break;
case 54:R=((/*RF2*/(((T54*)C))->_nb_emprunt/*i5p*/));

break;
default: error2(C,position);
}
}
set_dump_stack_top(caller);/*unlink*/
return R;
}/*--*/

#ifdef __cplusplus
}
#endif
